"""Auth service - registration, login, token refresh.

Registration flow (Phase 0):
1. Validate email + password strength
2. Create tenant (auto slug from email)
3. Create user in tenant schema (with bcrypt-hashed password)
4. Mark user as tenant_admin (first user of a tenant is always admin)
5. Issue access + refresh token pair
6. Return TokenResponse

Login flow:
1. Look up user by email across tenants (Phase 0: assume 1 user = 1 tenant)
2. Verify password
3. Issue new token pair

Refresh flow:
1. Verify refresh token signature + expiration
2. Issue new access token (refresh token rotation is Phase 1)
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from sqlalchemy import select
from sqlalchemy.exc import IntegrityError

from omnibase.auth.security import (
    TokenInvalid,
    create_token_pair,
    decode_refresh_token,
    hash_password,
    verify_password,
)
from omnibase.core.config import Settings, get_settings
from omnibase.core.db import get_engine, get_session_factory
from omnibase.core.logging import get_logger
from omnibase.db.tenant import User
from omnibase.onboarding import ensure_default_onboarding_assets
from omnibase.tenants.context import tenant_scope
from omnibase.tenants.service import (
    TenantAlreadyExists,
    create_tenant,
)

log = get_logger(__name__)


# -----------------------------------------------------------
# Errors
# -----------------------------------------------------------
class AuthError(Exception):
    """Base class for auth business errors."""


class EmailAlreadyRegistered(AuthError):
    """Email already exists in this tenant."""


class InvalidCredentials(AuthError):
    """Email/password mismatch."""


class UserInactive(AuthError):
    """User account is deactivated."""


# -----------------------------------------------------------
# Helpers
# -----------------------------------------------------------
_PASSWORD_STRENGTH = re.compile(
    # At least 8 chars, must contain a letter and a number (Phase 0 minimum)
    r"^(?=.*[A-Za-z])(?=.*\d).{8,}$"
)


def _validate_password_strength(password: str) -> None:
    """Raise ValueError if password is too weak."""
    if not _PASSWORD_STRENGTH.match(password):
        raise ValueError(
            "Password must be at least 8 characters and contain both " "letters and numbers"
        )


def _slug_from_email(email: str) -> str:
    """Derive a tenant display name + slug from an email address.

    Example: alice@example.com -> display "alice", slug auto-generated by service.
    """
    local_part = email.split("@", 1)[0]
    # Strip to alphanumerics + hyphens; fallback to "user"
    name = re.sub(r"[^a-zA-Z0-9-]", "", local_part).lower() or "user"
    return name[:50]


# -----------------------------------------------------------
# Data carrier (avoids circular imports between service and router)
# -----------------------------------------------------------
@dataclass(frozen=True)
class AuthResult:
    """Result of a successful register/login."""

    access_token: str
    refresh_token: str
    access_expires_at: object  # datetime, but kept loose for dataclass frozen
    refresh_expires_at: object
    user: User
    tenant: object  # Tenant, kept loose to avoid import cycle


# -----------------------------------------------------------
# Registration
# -----------------------------------------------------------
def register(
    *,
    email: str,
    password: str,
    tenant_name: str | None = None,
    settings: Settings | None = None,
) -> AuthResult:
    """Register a new user with an auto-created default tenant.

    Raises:
        ValueError: password too weak
        EmailAlreadyRegistered: email exists in the auto-created tenant
        TenantError / TenantAlreadyExists: tenant creation failed
    """
    settings = settings or get_settings()
    email = email.lower().strip()

    _validate_password_strength(password)
    password_hash = hash_password(password)

    # Derive tenant display name
    tenant_display_name = tenant_name or _slug_from_email(email)

    # 1. Create tenant (this also bootstraps the tenant schema + business tables)
    try:
        tenant = create_tenant(name=tenant_display_name, is_default=True)
    except TenantAlreadyExists as exc:
        # Extremely unlikely: auto-generated slug collision. Retry once.
        log.warning("register.tenant_slug_collision", email=email, error=str(exc))
        tenant = create_tenant(name=f"{tenant_display_name}-2", is_default=True)

    # 2. Insert user into the tenant's schema (auto search_path via contextvar)
    factory = get_session_factory(settings)
    with tenant_scope(tenant.schema_name):
        session = factory()
        try:
            user = User(
                email=email,
                password_hash=password_hash,
                is_tenant_admin=True,  # First user of a new tenant is admin
                is_active=True,
            )
            session.add(user)
            try:
                session.flush()
            except IntegrityError as exc:
                session.rollback()
                # Should be near-impossible: brand-new schema. Surface as conflict.
                raise EmailAlreadyRegistered(
                    f"Email {email!r} already exists in this tenant"
                ) from exc

            ensure_default_onboarding_assets(
                session,
                tenant_id=str(tenant.id),
                actor_user_id=str(user.id),
                # Control-plane request IDs use the shared safe identifier
                # alphabet; ':' would make first-user onboarding fail after
                # the tenant schema had already been bootstrapped.
                request_id=f"registration-{user.id}",
            )

            session.commit()
            session.refresh(user)

            log.info(
                "auth.user_registered",
                user_id=user.id,
                email=user.email,
                tenant_id=tenant.id,
                schema=tenant.schema_name,
            )

            # 3. Issue tokens
            access, refresh, access_exp, refresh_exp = create_token_pair(
                user_id=user.id,
                tenant_id=str(tenant.id),
                schema_name=tenant.schema_name,
                email=user.email,
                settings=settings,
            )

            return AuthResult(
                access_token=access,
                refresh_token=refresh,
                access_expires_at=access_exp,
                refresh_expires_at=refresh_exp,
                user=user,
                tenant=tenant,
            )
        finally:
            session.close()


# -----------------------------------------------------------
# Login
# -----------------------------------------------------------
def login(
    *,
    email: str,
    password: str,
    settings: Settings | None = None,
) -> AuthResult:
    """Authenticate a user and issue tokens.

    Phase 0 simplification: assumes 1 user = 1 tenant (the auto-created one).
    Phase 2 will add multi-tenant membership resolution.
    """
    settings = settings or get_settings()
    email = email.lower().strip()

    # Find the tenant that contains this user.
    # Phase 0: iterate active tenants and probe the users table.
    # This is O(n_tenants); fine for self-hosted personal use.
    from omnibase.tenants.schema_manager import list_active_tenant_schemas

    engine = get_engine(settings)
    factory = get_session_factory(settings)

    candidate_schemas = list_active_tenant_schemas(engine)
    log.debug("login.probing_tenants", email=email, count=len(candidate_schemas))

    for schema_name in candidate_schemas:
        with tenant_scope(schema_name):
            session = factory()
            try:
                stmt = select(User).where(User.email == email, User.is_active.is_(True))
                user = session.execute(stmt).scalar_one_or_none()
                if user is None:
                    continue  # Not in this tenant

                # Found the user - verify password
                if not verify_password(password, user.password_hash):
                    log.warning(
                        "login.password_mismatch",
                        email=email,
                        schema=schema_name,
                    )
                    raise InvalidCredentials("Invalid email or password")

                # Look up the Tenant row (in omnibase_meta) for this schema
                from omnibase.db.models import Tenant

                tenant_stmt = select(Tenant).where(Tenant.schema_name == schema_name)
                tenant = session.execute(tenant_stmt).scalar_one()

                access, refresh, access_exp, refresh_exp = create_token_pair(
                    user_id=user.id,
                    tenant_id=str(tenant.id),
                    schema_name=schema_name,
                    email=user.email,
                    settings=settings,
                )

                log.info(
                    "auth.user_logged_in",
                    user_id=user.id,
                    tenant_id=tenant.id,
                    schema=schema_name,
                )

                return AuthResult(
                    access_token=access,
                    refresh_token=refresh,
                    access_expires_at=access_exp,
                    refresh_expires_at=refresh_exp,
                    user=user,
                    tenant=tenant,
                )
            finally:
                session.close()

    # No tenant contained this user
    log.warning("login.user_not_found", email=email)
    # Same error as password mismatch to avoid user enumeration
    raise InvalidCredentials("Invalid email or password")


# -----------------------------------------------------------
# Refresh
# -----------------------------------------------------------
def refresh_access_token(
    *,
    refresh_token: str,
    settings: Settings | None = None,
) -> tuple[str, int]:
    """Exchange a refresh token for a new access token.

    Returns:
        (new_access_token, expires_in_seconds)

    Phase 1: rotate refresh token + revoke old jti in Redis.
    """
    settings = settings or get_settings()

    try:
        payload = decode_refresh_token(refresh_token, settings)
    except TokenInvalid as exc:
        log.warning("refresh.invalid_token", error=str(exc))
        raise InvalidCredentials("Invalid refresh token") from exc

    # Re-resolve canonical tenant state. A refresh token's schema claim is
    # historical metadata, never authority for a newly issued access token.
    from omnibase.tenants.service import TenantNotFound, get_tenant_by_id

    try:
        tenant = get_tenant_by_id(payload.tenant_id)
    except TenantNotFound as exc:
        raise InvalidCredentials("Invalid refresh token") from exc

    factory = get_session_factory(settings)
    with tenant_scope(tenant.schema_name):
        session = factory()
        try:
            user = session.execute(
                select(User).where(User.id == payload.sub, User.is_active.is_(True))
            ).scalar_one_or_none()
        finally:
            session.close()
    if user is None:
        raise InvalidCredentials("Invalid refresh token")

    # Issue new access token only (do NOT mint a new refresh - rotation is Phase 1)
    access, _, access_exp, _ = create_token_pair(
        user_id=user.id,
        tenant_id=str(tenant.id),
        schema_name=tenant.schema_name,
        email=user.email,
        settings=settings,
    )

    expires_in = int((access_exp - payload.exp).total_seconds())
    # Fallback if timing math is off
    if expires_in <= 0:
        expires_in = settings.access_token_expire_minutes * 60

    log.info("auth.token_refreshed", user_id=payload.sub, jti=payload.jti)
    return access, expires_in


__all__ = [
    "AuthError",
    "AuthResult",
    "EmailAlreadyRegistered",
    "InvalidCredentials",
    "UserInactive",
    "login",
    "refresh_access_token",
    "register",
]
