"""P5.4A engineering-only typed single-Agent Executor."""

from omnibase.agent_executor.contracts import (
    KNOWLEDGE_SEARCH_CAPABILITY,
    KNOWLEDGE_SEARCH_TOOL_ID,
    ExecutorContractError,
    ExecutorInvocationContext,
    ExecutorNodeResult,
    ExecutorToolReceipt,
    KnowledgeSearchHit,
    KnowledgeSearchPort,
    KnowledgeSearchRequest,
    KnowledgeSearchResult,
)
from omnibase.agent_executor.engineering import (
    ENGINEERING_FLAG,
    EXPECTED_MIGRATION_HEAD,
    EngineeringCompositionError,
    EngineeringCompositionUnavailable,
    EngineeringSingleAgentExecutor,
    LiveRuntimeAuthorityValidator,
    ServerWorkloadCredentialSeam,
    UnavailableEngineeringSingleAgentExecutor,
    build_engineering_executor,
    build_engineering_single_agent_executor,
)
from omnibase.agent_executor.gateway_adapter import (
    CapabilityGatewayKnowledgeSearchPort,
    GatewayAdapterDenied,
    GatewayAdapterError,
    GatewayAdapterUnavailable,
    RuntimeAuthorityValidator,
    ServerWorkloadCredentialProvider,
    SessionFactory,
)
from omnibase.agent_executor.service import (
    TypedExecutorError,
    TypedExecutorPolicyDenied,
    TypedExecutorUnavailable,
    TypedSingleAgentExecutor,
    UnavailableTypedSingleAgentExecutor,
    build_engineering_typed_executor,
)

__all__ = [
    "ENGINEERING_FLAG",
    "EXPECTED_MIGRATION_HEAD",
    "KNOWLEDGE_SEARCH_CAPABILITY",
    "KNOWLEDGE_SEARCH_TOOL_ID",
    "CapabilityGatewayKnowledgeSearchPort",
    "EngineeringCompositionError",
    "EngineeringCompositionUnavailable",
    "EngineeringSingleAgentExecutor",
    "ExecutorContractError",
    "ExecutorInvocationContext",
    "ExecutorNodeResult",
    "ExecutorToolReceipt",
    "GatewayAdapterDenied",
    "GatewayAdapterError",
    "GatewayAdapterUnavailable",
    "KnowledgeSearchHit",
    "KnowledgeSearchPort",
    "KnowledgeSearchRequest",
    "KnowledgeSearchResult",
    "LiveRuntimeAuthorityValidator",
    "RuntimeAuthorityValidator",
    "ServerWorkloadCredentialProvider",
    "ServerWorkloadCredentialSeam",
    "SessionFactory",
    "TypedExecutorError",
    "TypedExecutorPolicyDenied",
    "TypedExecutorUnavailable",
    "TypedSingleAgentExecutor",
    "UnavailableEngineeringSingleAgentExecutor",
    "UnavailableTypedSingleAgentExecutor",
    "build_engineering_executor",
    "build_engineering_single_agent_executor",
    "build_engineering_typed_executor",
]
