"""P34.5 provider-neutral Overlay adapter and trusted Node Daemon seams."""

from omnibase.workspaces.overlay_adapters.contracts import (
    CredentialReferenceIssuer,
    NodeDaemonAttestor,
    OverlayAction,
    OverlayAdapterError,
    OverlayBindingVerifier,
    OverlayDaemonCommand,
    OverlayDaemonReceipt,
    OverlayLogicalServicePublication,
    OverlayOperationIntent,
    OverlayOperationLedger,
    OverlayOperationReservation,
    OverlayOutcomeUnknown,
    OverlayPublicationMode,
    OverlayRejected,
    OverlayState,
    OverlaySubjectKind,
    OverlayUnavailable,
    RejectingCredentialReferenceIssuer,
    RejectingNodeDaemonAttestor,
    RejectingOverlayBindingVerifier,
    RejectingOverlayOperationLedger,
    ShortLivedCredentialReference,
    VerifiedNodeDaemon,
    VerifiedOverlayBinding,
    overlay_operation_binding_digest,
)
from omnibase.workspaces.overlay_adapters.headscale import HeadscaleOverlayAdapter
from omnibase.workspaces.overlay_adapters.ledger import (
    InMemoryOverlayOperationLedger,
    SqliteOverlayOperationLedger,
)
from omnibase.workspaces.overlay_adapters.transport import (
    CliOverlayDaemonTransport,
    CliResult,
    HttpJsonResponse,
    HttpOverlayDaemonTransport,
    InjectedCliRunner,
    InjectedHttpJsonClient,
    MtlsHttpJsonClient,
    OverlayDaemonTransport,
    UnavailableOverlayDaemonTransport,
)

__all__ = [
    "CliOverlayDaemonTransport",
    "CliResult",
    "CredentialReferenceIssuer",
    "HeadscaleOverlayAdapter",
    "HttpJsonResponse",
    "HttpOverlayDaemonTransport",
    "InMemoryOverlayOperationLedger",
    "InjectedCliRunner",
    "InjectedHttpJsonClient",
    "MtlsHttpJsonClient",
    "NodeDaemonAttestor",
    "OverlayAction",
    "OverlayAdapterError",
    "OverlayBindingVerifier",
    "OverlayDaemonCommand",
    "OverlayDaemonReceipt",
    "OverlayDaemonTransport",
    "OverlayLogicalServicePublication",
    "OverlayOperationIntent",
    "OverlayOperationLedger",
    "OverlayOperationReservation",
    "OverlayOutcomeUnknown",
    "OverlayPublicationMode",
    "OverlayRejected",
    "OverlayState",
    "OverlaySubjectKind",
    "OverlayUnavailable",
    "RejectingCredentialReferenceIssuer",
    "RejectingNodeDaemonAttestor",
    "RejectingOverlayBindingVerifier",
    "RejectingOverlayOperationLedger",
    "ShortLivedCredentialReference",
    "SqliteOverlayOperationLedger",
    "UnavailableOverlayDaemonTransport",
    "VerifiedNodeDaemon",
    "VerifiedOverlayBinding",
    "overlay_operation_binding_digest",
]
