"""P34.5A fail-closed Sandbox foundation and A1-A2 dispatch contracts.

No implementation in this package executes code or contacts a runtime,
container engine, network provider, data store or host control socket.
"""

from omnibase.sandbox.authorization import (
    ComposedSandboxAuthorizer,
    RejectingSandboxCapabilityVerifier,
    RejectingSandboxLeaseVerifier,
    SqlAlchemySandboxLeaseVerifier,
    VerifiedSandboxCapability,
    VerifiedSandboxLease,
)
from omnibase.sandbox.contracts import (
    RejectingSandboxAuthorizer,
    SandboxAction,
    SandboxAuthorizer,
    SandboxCommandSpec,
    SandboxConflict,
    SandboxExecutionDisabled,
    SandboxIsolationPolicy,
    SandboxNetworkMode,
    SandboxNetworkPolicy,
    SandboxOperationRequest,
    SandboxProvider,
    SandboxRejected,
    SandboxRelativePath,
    SandboxResourceLimits,
    SandboxRuntimeHandle,
    SandboxRuntimeSpec,
    SandboxRuntimeState,
    SandboxRuntimeView,
    SandboxSnapshot,
    SandboxUnavailable,
    VerifiedSandboxAuthorization,
)
from omnibase.sandbox.control import (
    InMemorySandboxControlAuthorizer,
    RejectingSandboxControlAuthorizer,
    SandboxControlAction,
    SandboxControlRequest,
    VerifiedSandboxControlAuthorization,
)
from omnibase.sandbox.coordinator import (
    SandboxDispatchResult,
    SandboxExecutionCoordinator,
)
from omnibase.sandbox.host import (
    RejectingRunnerHostAttestor,
    RunnerHostAttestor,
    VerifiedRunnerHost,
)
from omnibase.sandbox.operations import (
    InMemorySandboxOperationStore,
    SandboxOperationIntent,
    SandboxOperationState,
    SandboxOperationStore,
    UnavailableSandboxOperationStore,
)
from omnibase.sandbox.provider import (
    FakeInMemorySandboxProvider,
    InMemorySandboxAuthorizer,
    UnavailableSandboxProvider,
)
from omnibase.sandbox.runner import (
    RunnerExecutionPlan,
    RunnerIsolationProfile,
    RunnerPlatform,
    RunnerReceipt,
    RunnerTerminationPlan,
    UnavailableSandboxRunner,
)
from omnibase.sandbox.transport import (
    RunnerOutcomeUnknown,
    RunnerTransport,
    UnavailableRunnerTransport,
)

__all__ = [
    "ComposedSandboxAuthorizer",
    "FakeInMemorySandboxProvider",
    "InMemorySandboxAuthorizer",
    "InMemorySandboxControlAuthorizer",
    "InMemorySandboxOperationStore",
    "RejectingRunnerHostAttestor",
    "RejectingSandboxAuthorizer",
    "RejectingSandboxCapabilityVerifier",
    "RejectingSandboxControlAuthorizer",
    "RejectingSandboxLeaseVerifier",
    "RunnerExecutionPlan",
    "RunnerHostAttestor",
    "RunnerIsolationProfile",
    "RunnerOutcomeUnknown",
    "RunnerPlatform",
    "RunnerReceipt",
    "RunnerTerminationPlan",
    "RunnerTransport",
    "SandboxAction",
    "SandboxAuthorizer",
    "SandboxCommandSpec",
    "SandboxConflict",
    "SandboxControlAction",
    "SandboxControlRequest",
    "SandboxDispatchResult",
    "SandboxExecutionCoordinator",
    "SandboxExecutionDisabled",
    "SandboxIsolationPolicy",
    "SandboxNetworkMode",
    "SandboxNetworkPolicy",
    "SandboxOperationIntent",
    "SandboxOperationRequest",
    "SandboxOperationState",
    "SandboxOperationStore",
    "SandboxProvider",
    "SandboxRejected",
    "SandboxRelativePath",
    "SandboxResourceLimits",
    "SandboxRuntimeHandle",
    "SandboxRuntimeSpec",
    "SandboxRuntimeState",
    "SandboxRuntimeView",
    "SandboxSnapshot",
    "SandboxUnavailable",
    "SqlAlchemySandboxLeaseVerifier",
    "UnavailableRunnerTransport",
    "UnavailableSandboxOperationStore",
    "UnavailableSandboxProvider",
    "UnavailableSandboxRunner",
    "VerifiedRunnerHost",
    "VerifiedSandboxAuthorization",
    "VerifiedSandboxCapability",
    "VerifiedSandboxControlAuthorization",
    "VerifiedSandboxLease",
]
