"""Cross-platform local runtime contracts."""

from omnibase.runtime.capabilities import (
    CapabilityReport,
    EvidenceState,
    ExecutionBackend,
    PortStatus,
    ProductMode,
    check_port,
    probe_capabilities,
    probe_network_state,
    suggest_port,
)
from omnibase.runtime.diagnostics import (
    MAX_COLLECTION_SIZE,
    MAX_REDACTION_DEPTH,
    MAX_STRING_LENGTH,
    ServiceStatus,
    diagnostics_json,
    diagnostics_payload,
    redact_mapping,
    select_mode,
)
from omnibase.runtime.lifecycle import (
    ALLOWED_SERVICES,
    ALLOWED_VERBS,
    APPROVED_PROFILES,
    DEFAULT_LIFECYCLE_TIMEOUT,
    DEFAULT_LOG_TAIL,
    LifecycleRequest,
    LifecycleResult,
    doctor,
    health,
    logs,
    ports_status,
    start,
    status,
    stop,
    suggest_port_command,
    validate_request,
)
from omnibase.runtime.lifecycle import (
    capabilities as lifecycle_capabilities,
)

__all__ = [
    "ALLOWED_SERVICES",
    "ALLOWED_VERBS",
    "APPROVED_PROFILES",
    "DEFAULT_LIFECYCLE_TIMEOUT",
    "DEFAULT_LOG_TAIL",
    "MAX_COLLECTION_SIZE",
    "MAX_REDACTION_DEPTH",
    "MAX_STRING_LENGTH",
    "CapabilityReport",
    "EvidenceState",
    "ExecutionBackend",
    "LifecycleRequest",
    "LifecycleResult",
    "PortStatus",
    "ProductMode",
    "ServiceStatus",
    "check_port",
    "diagnostics_json",
    "diagnostics_payload",
    "doctor",
    "health",
    "lifecycle_capabilities",
    "logs",
    "ports_status",
    "probe_capabilities",
    "probe_network_state",
    "redact_mapping",
    "select_mode",
    "start",
    "status",
    "stop",
    "suggest_port",
    "suggest_port_command",
    "validate_request",
]
